/* eslint-disable react/no-unescaped-entities */
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Head from "next/head";
import HomeSection from "./Home-Section";
import ToolsSection from "./Tools-Section";
import PortfolioSection from "./Portfolio-Section";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Noel Yohannes Ghebremeskel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Nav Bar Component of the Portfolio Website */}
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-black">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              Developed by Noel
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-teal-500 hover:bg-teal-600 active:bg-teal-500 focus:outline-none focus:ring focus:ring-teal-300 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1WCQzI477BOLs0DxZYH71a3zN4CpejV2Q/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* Home Component of the Portfolio Website */}
          <HomeSection />
        </section>

        {/* Tools/Technologies Component of the Portfolio Website */}
        <ToolsSection />

        {/* Portfolio Component of the Portfolio Website */}
        <PortfolioSection />
      </main>
    </div>
  );
}
